version: '3.9'

services:
  web:
    build:
      context: https://github.com/kfwalder/siteMatoGrosso2.git
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
