# Usa imagem oficial Python
FROM python:3.12-slim

# Define diretório de trabalho no container
WORKDIR /app

# Copia dependências
COPY requirements.txt .

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código
COPY . .

# Expõe a porta que o Django usa
EXPOSE 8000

# Comando para rodar o servidor de desenvolvimento
CMD ["python", "app/manage.py", "runserver", "0.0.0.0:8000"]
