version: '3.9'

services:
  web:
    build:
      context: https://github.com/kfwalder/siteMatoGrosso2.git
      dockerfile: DockerFile
    ports:
      - "9000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
    volumes:
      - .:/volume1
