# Generated by Django 5.2.2 on 2025-06-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outdoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('dimensao', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
    ]
