# Generated by Django 5.2.2 on 2025-06-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_outdoor_ponto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(choices=[('AEROPORTO', 'AEROPORTO'), ('BUSDOOR', 'BUSDOOR'), ('CONTAINERS', 'CONTAINERS'), ('EMPENAS', 'EMPENAS'), ('FRONT-LIGHT', 'FRONT-LIGHT'), ('MEGA-PAINEL', 'MEGA-PAINEL'), ('MOBILIÁRIO URBANO', 'MOBILIÁRIO URBANO'), ('OUTDOOR', 'OUTDOOR'), ('PAINÉIS RODOVIÁRIO', 'PAINÉIS RODOVIÁRIO'), ('PAINEL DE LED', 'PAINEL DE LED'), ('PLACA DE ESQUINA', 'PLACA DE ESQUINA'), ('TOP-SIGHT', 'TOP-SIGHT'), ('TOTEM / TOTEM DIGITAL', 'TOTEM / TOTEM DIGITAL')], max_length=30),
        ),
    ]
