# Generated by Django 5.2.2 on 2025-06-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ponto_dimensao_alter_ponto_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_upload/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
