# Generated by Django 5.2.2 on 2025-06-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_imagemupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='teste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
