# Generated by Django 5.2.2 on 2025-06-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ponto_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
