# Generated by Django 5.2.2 on 2025-06-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ponto_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='teste',
            field=models.CharField(blank=True, db_column='teste', max_length=20, null=True),
        ),
        migrations.RenameField(
            model_name='ponto',
            old_name='teste',
            new_name='teste2',
        ),
    ]
