# Generated by Django 5.2.2 on 2025-06-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_local_remove_ponto_teste2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='local_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.local'),
        ),
    ]
