# Generated by Django 5.2.2 on 2025-06-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ponto_local_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='local',
        ),
    ]
