# Generated by Django 5.2.2 on 2025-06-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_ponto_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='prioridade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
